[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via_ir = true
solc = "0.8.20"
# bytecode_hash = "none"
optimizer_runs = 1000000

[dependencies]
forge-std = "1.9.5"
"@openzeppelin/contracts" = "5.0.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
bitfinity = "${RPC_URL}"

[fmt]
number_underscore = "thousands"
